#!/bin/bash
#
# cmms_file_import_daemon.pl        Startup script for the CMMS File Daemon
#
# chkconfig: 2345 89 20
# description: Daemon for CMMS File importer
# processname: cmms_file_import_daemon.pl

# Source function library.
. /etc/rc.d/init.d/functions

# Path to binary
daemon=/usr/bin/cmms_file_import_daemon.pl
prog=cmms
RETVAL=0

# subs
getpids() {
        PIDS=`ps -efww | grep perl | grep $prog | grep -v ripper | grep -v player | awk {'print $2'}`
	PIDS=`echo ${PIDS//\n/''}`
        [ -z "$PIDS" ] && return 1 || return 0
}
start() {
        echo -n $"Starting $prog: "
        $daemon 1>/usr/local/cmms/logs/file_importer.log 2>&1 &
        RETVAL=$?
        return $RETVAL
}
stop() {
	echo -n $"Stopping $prog: "
	getpids && [ -w / ] && kill $PIDS
	RETVAL=$?
	return $RETVAL
}
status() {
	if getpids ; then
		echo "$prog ($PIDS) is running..."
	else
		echo "$prog is stopped"
		RETVAL=1
	fi
	echo
}

# See how we were called.
case "$1" in
  start)
	if getpids ; then
		echo "$prog ($PIDS) is already running..."
	else
		start && success || failure
	fi
	echo
	;;
  stop)
	stop && success || failure
	echo
	;;
  status)
        status
	RETVAL=$?
	;;
  restart)
        stop && success || failure
        echo
        start && success || failure
        echo
        ;;
  condrestart)
        if getpids ; then
                stop && success || failure
                echo
                start && success || failure
                echo
        else
                echo "$prog is stopped"
        fi
	;;
  *)
	echo $"Usage: cmmsfiled {start|stop|restart|condrestart|status}"
	exit 1
esac

exit $RETVAL
